name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install clang-tidy
        run: sudo apt install clang-tidy

      - name: Build application
        run: ./build.sh